version: '3.8'
services:
  frontend:
    build: ./frontend
    image: todo-frontend
    container_name: todo-frontend
    ports:
      - 8080:5173
    volumes:
      - ./frontend/app:/usr/src/app
    depends_on:
      - flask
  backend:
    build: ./backend
    image: todo-backend
    container_name: todo-backend
    ports:
      - 8081:8000
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:9.0
    platform: linux/arm64
    container_name: mysql-todo
    ports:
      - 3306:3306
    restart: always
    env_file:
      - ./.env_file/mysql.env
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
