version: '3.8'
services:
  nginx:
    image: nginx:1.26.2
    platform: linux/arm64
    container_name: todo-nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
  frontend:
    build: ./frontend
    image: todo-frontend
    container_name: todo-frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend/app:/usr/src/app
    tty: true
    stdin_open: true
    depends_on:
      - backend
  backend:
    build: ./backend
    image: todo-backend
    container_name: todo-backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/app
    tty: true
    stdin_open: true
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:9.0
    platform: linux/arm64
    container_name: todo-db
    ports:
      - 3306:3306
    restart: always
    env_file:
      - ./.env_file/mysql.env
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - db-store:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  db-store: