version: '3.8'
services:
  nginx:
    image: nginx:1.26.2
    platform: linux/arm64
    container_name: todo-nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
  frontend:
    build: ./frontend
    image: todo-frontend
    container_name: todo-frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend/app:/usr/src/app
    tty: true
    stdin_open: true
    depends_on:
      - backend
  backend:
    build: ./backend
    image: todo-backend
    container_name: todo-backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/app
    tty: true
    stdin_open: true
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.6
    platform: linux/arm64
    container_name: todo-db
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./db/config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./db/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  db-store: